imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
 
# Twig Configuration 
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
      resources:
        - bootstrap_3_layout.html.twig
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
      naming_strategy: "doctrine.orm.naming_strategy.underscore"
      auto_generate_proxy_classes: %kernel.debug%
      auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

sensio_framework_extra:
    view: { annotations: false }

#fos_rest:
#    disable_csrf_role: ROLE_API
#    param_fetcher_listener: true
#    view:
#        mime_types:
#            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
#        view_response_listener: 'force'
#        formats:
#            xml:  true
#            json: true
#        templating_formats:
#            html: true
#    format_listener:
#        rules:
#            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
#        media_type:
#            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
#    exception:
#        codes:
#            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
#            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
#        messages:
#            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
#    allowed_methods_listener: true
#    access_denied_listener:
#        json: true
#    body_listener: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ife\AloesBundle\Entity\User
  
fr3d_ldap:
    driver:
        host: %fr3d_ldap_host%
    user:
        baseDn: ou=people, dc=ens-lyon, dc=fr    
        filter: (&(ObjectClass=Person))
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
            - { ldap_attr: uid,  user_method: setUsername } # Default
            - { ldap_attr: mail,   user_method: setEmail }  # Optional 
            - { ldap_attr: sn,   user_method: setSn }  # Optional
            - { ldap_attr: givenname,   user_method: setGivenname }  # Optional
               
# sn nom de famille   
                
#fos_http_cache:
#    cache_control:
#        rules:
            # the controls section values are used in a call to Response::setCache();
#            -
#                match:
#                    path: ^/notes
#                    methods: [GET, HEAD]
#                headers:
#                    cache_control: { public: true, max_age: 15, s_maxage: 30 }
#                    last_modified: "-1 hour"
#                    vary: [Accept-Encoding, Accept-Language]
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%
    theme:
        simple:
            plugins: ["code,preview,link,fullscreen "] 
            menubar: false
            statusbar: true 
            toolbar1: "code preview | bold italic | alignleft aligncenter alignright alignjustify| bullist numlist outdent indent | link fullscreen" 


 
sc_datetimepicker: 
    picker: ~           
