ife_aloes:
  resource: "@IfeAloesBundle/Resources/config/routing.yml"
  prefix:   /aloes

ife_aloes_public:
  resource: "@IfeAloesBundle/Resources/config/routing-public.yml"
  prefix:   /aloes-public

ife_aloes_admin:
  resource: "@IfeAloesBundle/Resources/config/routing-admin.yml"
  prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
