security:

    erase_credentials: false

    firewalls:
        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider 
                always_use_default_target_path: true
                default_target_path: /aloes/programs/list            
            logout:        
                path:   fos_user_security_logout
                target: /login                  
            anonymous:    true
 
  
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle,fr3d_ldapbundle]         

        fr3d_ldapbundle: 
            id: fr3d_ldap.security.user.provider         
         
        fos_userbundle: 
            id: fos_user.user_manager
 
    encoders:
#       Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: plaintext    
 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN,ROLE_RESPONSABLE,ROLE_ENSEIGNANT]
        ROLE_RESPONSABLE: [ROLE_RESPONSABLE,ROLE_ENSEIGNANT]
        ROLE_ENSEIGNANT: ROLE_ENSEIGNANT        
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
 
 
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # 
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }    
        - { path: ^/aloes/, role: IS_AUTHENTICATED_FULLY }  
        - { path: ^/aloes-public/, role: IS_AUTHENTICATED_ANONYMOUSLY } 

                
                
