event:
    path:     /
    defaults: { _controller: "IfeAloesBundle:Event:index" }
  
event_show:
    path:     /{id}/show
    defaults: { _controller: "IfeAloesBundle:Event:show" }

event_new:
    path:     /new
    defaults: { _controller: "IfeAloesBundle:Event:new" }

event_create:
    path:     /create
    defaults: { _controller: "IfeAloesBundle:Event:create" }
    requirements: { _method: post }

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "IfeAloesBundle:Event:edit" }

event_update:
    path:     /{id}/update
    defaults: { _controller: "IfeAloesBundle:Event:update" }
    requirements: { _method: post|put }

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "IfeAloesBundle:Event:delete" }

