<?php

namespace Ife\AloesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Ife\AloesBundle\AloesModel\ResultIndexerTrait;
 
/**
 * SpecificObjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentObjectiveRepository extends EntityRepository
{
    public function findCourse($course,$assessment_id = 0)
    { 
    	
	$db = $this->getEntityManager()->getConnection();		
		
    $sql = "
		SELECT general_objective.id AS gc_id, general_objective.title AS gc_title, specific_objective.id AS sc_id, specific_objective.title AS sc_title
		FROM general_objective, specific_objective
		WHERE general_objective.id = specific_objective.general_objective_id
		AND specific_objective.course_id = ".$course."
		ORDER BY general_objective_id
		";   
     
	$ocs=array();
		
	$result = $db->fetchAll($sql);  		
		
	foreach ($result as $res)
		{	  
		$oc=array();		
		$oc['gc_id']		= 	$res['gc_id'];
		$oc['gc_title']		= 	$res['gc_title'];
		$oc['sc_id']		= 	$res['sc_id'];
		$oc['sc_title']		= 	$res['sc_title'];
		$oc['rating']		= 	0;
		

		$ocs[$res['gc_id']."#".$res['sc_id']]=$oc;		 
		}
		
 
    $sql2 = "select * from assessment_objective,specific_objective 
    		where assessment_objective.objective_id=specific_objective.id  and assessment_id=".$assessment_id;   		
	$result2 = $db->fetchAll($sql2);  
	foreach ($result2 as $res2)
		{	   
		$tmp = $ocs[$res2['general_objective_id']."#".$res2['objective_id']];
		$tmp['rating']=$res2['rating'];
		$ocs[$res2['general_objective_id']."#".$res2['objective_id']]=$tmp;
		}
		
    return $ocs;        
    }
  
}
