<?php

namespace Ife\AloesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Ife\AloesBundle\AloesModel\ResultIndexerTrait;

/**
 * SpecificObjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificObjectiveRepository extends EntityRepository
{
//    use ResultIndexerTrait;

    private function groupRowsBy($data, $key = 'parent_id')
    {
        $result = array();
        foreach($data as $row) {
            $result[$row[$key]][] = $row;
        }
        return $result;
    }

    private function indexWeightsById($data, $key = 'id')
    {
        $result = array();
        foreach($data as $row) {
            $result[$row[$key]] = $row['weight'];
        }
        return $result;
    }	
	
	
    public function findWeightsByCourse($course)
    {
        $sql = "
		SELECT objective_id AS id, weight 
		FROM course_objective_weight
		WHERE course_id = ?
		";
        $conn = $this->_em->getConnection();
        $stmt = $conn->executeQuery($sql, array($course->getId()));
        $data = $stmt->fetchAll();
        return $this->indexWeightsById($data);        
    }
    
    public function findObjectiveCompetencefByCourse($course)
    {
    	$objectifCompetences = array(); 
    	
        $sql = "
		select specific_objective.id as id,specific_objective.position as position,specific_competence.id as comp,  specific_competence.title, objective_competence_weight.weight, objective_competence.rating		
		from specific_objective, objective_competence, specific_competence,objective_competence_weight		
		where   
		specific_objective.id=objective_competence.objective_id and
		specific_objective.id=objective_competence_weight.objective_id and		
		specific_objective.course_id=? and		
		objective_competence.competence_id = specific_competence.id and
		objective_competence.competence_id = objective_competence_weight.competence_id
		order by specific_objective.id,specific_competence.id 
		";
        $conn = $this->_em->getConnection();
        $stmt = $conn->executeQuery($sql, array($course->getId()));
        $data = $stmt->fetchAll();
        
        $obj_cur = "";
 		$competences = array();
 				       
		foreach ($data as $oc)
			{        
			if ( ($oc['id']!=$obj_cur) && ($obj_cur!=""))	
				{
				$objectifCompetences[$obj_cur]=	$competences;
				$competences = array();
				}
				
			$competence = array();
			$competence['comp']			=$oc['comp'];				
			$competence['title']		=$oc['title'];		
			$competence['weight']		=$oc['weight'];	
			$competence['rating']		=$oc['rating'];	
			$competences[$oc['comp']]	=$competence;
			
			$obj_cur = $oc['id']; 
			}
			
		if ($obj_cur!="")	
			$objectifCompetences[$obj_cur]=	$competences;
		
        
        return $objectifCompetences;        
    }    

    
    
      
    
    
    
    
}
